### PR TITLE
WIP: Introduce the idea of toolchains and add `perl_xs` rule

### PR DESCRIPTION
**Pull request by GregBowyer**
This is a WIP that introduces the idea of toolchains to the rules, and
uses this to download a toolchain for perl.

A downloadable toolchain is provided via the `deps.bzl` file to allow
for a hermetic in tree toolchain of perl. This toolchain is a
redistributable perl from `skaji` although it could probably be
reproduced under a different banner for practical reasons of toolchain
compliance.

Using the download toolchain is as follows:

```
load(
    "@io_bazel_rules_perl//perl:deps.bzl",
    "perl_register_toolchains",
    "perl_rules_dependencies",
)

perl_rules_dependencies()
perl_register_toolchains()
```

As part of these changes the perl launcher script was replaced with a
simpler shell script that covers launching `perl_binary` and `perl_test`
targets which is aware of the given bazel toolchain.

Along with these changes the `perl_xs` rule is introduced that allows
for perl extension modules to be _crudely_ compiled. This was needed by
us at $DAYJOB to get a bunch of cpan modules to be built that use
various C extensions (the test of these changes was `IO-Tty`).

### CODE REVIEW

**Comment by PiotrSikora** [comment]
@GregBowyer thanks for the contribution, let me see if we have someone who can actually review this. @qiwzhang could you take a pass?

@philwo I think we need a proper owners for this repo. I'm definitely not in a position to review this PR, neither on Bazel integration nor Perl side. Do we have anyone from the Bazel team that could own this?

**Comment by qiwzhang** [comment]
Sorry,  I don't have time to maintain this repo.  I like to release my ownership to someone else. @philwo  could you find someone from bazel tool team to own this?

**Comment by skeletonkey** [comment]
@googlebot I fixed it..

**Comment by laurentlb** [comment]
@GregBowyer 
We don't have any maintainer for rules_perl now. If you're using the rules, would you be interested in maintaining the repository?

**Comment by skeletonkey** [comment]
Greg did the heavy lifting on this, however, I'm the Perl nut so I'll be happy to be the maintainer.  I'm sure I'll be asking him many questions getting this up and running properly. I will be grateful for any tips/guidance that you guys may have for me!

**Comment by skeletonkey** [comment]
@googlebot I fixed it.

**Comment by skeletonkey** [comment]
@googlebot I fixed it.

**Comment by skeletonkey** [comment]
I was having some issue with getting a toolchain work for OSX, however, the big reveal was that Mac's use a .bundle or .bd instead of .so.  The plan has become to get this out the door for linux and then start working on expanding. 

An alternative is to get the toolchain for OSX working and set up the build/test targets to exclude the 'complex_deps'.  That way basic perl is available for OXS.

**Comment by skeletonkey** [comment]
Got the Mac toolchain working.  It can't do compiled Perl modules, but it supports all functionality that the current rules_perl version does for Mac.  Hopefully, that should follow soon.

Trying this one more time - since I have signed the CLA:
@googlebot I fixed it.

**Comment by PiotrSikora** [comment]
@skeletonkey you've used 3 different addresses in this PR, and neither `...@ticketmaster.com`,  nor `...@jundy.com` signed the CLA.

**Comment by skeletonkey** [comment]
I think I have it this time ... else I'll just go the consent route.

@googlebot I fixed it.

**Pull request merged**
