### PR TITLE
Allow C/C++ sources in "perl_xs" target.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
@skeletonkey note that while this can be used as a workaround for #24, it's also a valid feature on it's own (e.g. see how `FCGI` module used in examples is built using `perl Makefile.PL && make`).

**Comment by PiotrSikora** [comment]
@skeletonkey friendly ping.

**Comment by skeletonkey** [comment]
@PiotrSikora I apologize about the prolonged silence.  I have not gotten anywhere with this issue.  I have reached out to the PerlXS mailing list hoping that someone there will have ideas on how to move this forward.

**Comment by PiotrSikora** [comment]
@skeletonkey friendly ping.

**Comment by skeletonkey** [comment]
@PiotrSikora I've taken a look and haven't been able to figure out how to fix the merge conflicts for your branch.  Can you please make the minor fixes and then I can merge it.  Thanks for you patience.

**Comment by PiotrSikora** [comment]
@skeletonkey Done.

**Pull request merged**
