### PR TITLE
Replace find_cpp_toolchain with find_cc_toolchain

### PR DESCRIPTION
**Pull request by comius**
This properly resolve CPP toolchain when Cc toolchainisation is enabled.

### CODE REVIEW

**Comment by comius** [comment]
Hey @skeletonkey can I ask for a speedy review here? It's blocking Bazel LTS cut.

**Comment by skeletonkey** [comment]
@comius sorry for the delay.  Please confirm that this MR needs to happen before bazelbuild/bazel/pull/16252.  Are there any potential risks for committing this before that PR?

**Comment by comius** [comment]
> @comius sorry for the delay. Please confirm that this MR needs to happen before [bazelbuild/bazel/pull/16252](https://github.com/bazelbuild/bazel/pull/16252). Are there any potential risks for committing this before that PR?

Correct.

I don't think there are any risk. `find_cc_toolchain` is implemented defensively and should work with older Bazel versions. It's obtained from a fixed version of `rules_cc`.

**Comment by skeletonkey** [comment]
Thank you - merging it now.

**Pull request merged**
